### ISSUE TITLE
Cannot read properties of null (reading 'hasOwnProperty')

### ISSUE THREAD

**Issue by vrkansagara** [marlonfan/coc-phpls#104]
~~~bash
2021-11-07T21:01:08.917 ERROR (pid:14258) [source-language] - Complete "phpls" error: TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at /home/vallabh/github/coc-phpls/lib/index.js:98:29
    at async LanguageSource.doComplete (/home/vallabh/.vim/vendor/coc.nvim/build/index.js:59366:20)

~~~

**Comment by scottperlitch** [comment]
Not sure the root of the problem, but the following fixed the php comments issue as a workaround:

`Plug 'neoclide/coc.nvim', {'branch': 'release', 'commit': '0d9e7f65db1df0ff0946798c81097abafc018068'}`

```
cd ~/.vim/bundle/coc.nvim
yarn install
yarn build
```

**Comment by scottperlitch** [comment]
Not sure the root of the problem, but the following fixed the php comments issue as a workaround:

`Plug 'neoclide/coc.nvim', {'branch': 'release', 'commit': '0d9e7f65db1df0ff0946798c81097abafc018068', 'do': 'yarn install --frozen-lockfile'}`

**Comment by alekmlynek** [comment]
Thanks @scottperlitch for the workaround. For everyone else, don't burn 10 minutes like me and remember to:
- :CocRestart
- yarn install (In your CoC plugin directory)

**Comment by peterbabic** [comment]
> `Plug 'neoclide/coc.nvim', {'branch': 'release', 'commit': '0d9e7f65db1df0ff0946798c81097abafc018068', 'do': 'yarn install --frozen-lockfile'}`

This help but creates another problem for me: 

`[coc.nvim] Error on activate extension coc-prettier: import_coc6.window.onDidChangeActiveTextE
ditor is not a function `

**Comment by yaegassy** [comment]
I have created and maintain my own extension of coc.nvim for intelephense. Until the problem is fixed in `coc-phpls`, please try if you need.

- coc-intelephense 
  - <https://github.com/yaegassy/coc-intelephense>
  - `:CocInstall @yaegassy/coc-intelephense`

**Comment by jchook** [comment]
For me, this bug happens on macOS but not Linux.
