### ISSUE TITLE
Error: Unhandled method indexWorkspace

### ISSUE THREAD

**Issue by dietrichm** [marlonfan/coc-phpls#28]
**Describe the bug**
With the latest version of this extension, PHP workspaces are no longer being indexed.

**To Reproduce**
1. Install latest version of coc.nvim and coc-phpls.
2. Run `intelephense.index.workspace` through `:CocCommand`
3. The error `Error: Unhandled method indexWorkspace` is shown

**Expected behavior**
Messages regarding workspace being indexed are shown.

**Additional context**
Running `:CocOpenLog` reveals (home directory path snipped):
```
2019-08-14T16:45:38.988 INFO (pid:33693) [services] - registed service "phpls"
2019-08-14T16:45:38.990 INFO (pid:33693) [services] - PHP Language Server state change: stopped => starting
2019-08-14T16:45:39.001 INFO (pid:33693) [language-client-index] - phpls started with 33696
2019-08-14T16:45:39.009 INFO (pid:33693) [plugin] - coc 0.0.73-e9ef666cb5 initialized with node: v12.6.0
2019-08-14T16:45:39.769 INFO (pid:33693) [services] - PHP Language Server state change: starting => running
2019-08-14T16:45:39.775 INFO (pid:33693) [services] - service phpls started
2019-08-14T16:45:45.315 ERROR (pid:33693) [commands] - Error: Unhandled method indexWorkspace
    at handleResponse (../nvim/plugged/coc.nvim/build/index.js:38047:48)
    at processMessageQueue (../nvim/plugged/coc.nvim/build/index.js:37874:17)
    at Immediate.<anonymous> (../nvim/plugged/coc.nvim/build/index.js:37858:13)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by marlonfan** [comment]
Upstream projects have changed the way they are executed, I will follow up the modification recently.  Thank you for your feedback.

**Comment by marlonfan** [comment]
fixed

**Comment by dietrichm** [comment]
Verified working. Thanks for your work and the quick response!
